// This file contains the structured service categories and their respective services

export const serviceCategories = [
  {
    id: "ai-ml",
    name: "AI & Machine Learning",
    services: [
      "AI Chatbots & Virtual Assistants",
      "AI-Powered Business Insights",
      "Predictive Analytics & ML Solutions",
      "AI-Driven Marketing & Personalization",
      "AI Fraud Detection for Transactions",
      "AI Agents",
      "AI Consulting & Implementations",
      "Machine Learning Model Development",
      "Natural Language Processing Solutions",
      "Computer Vision Applications",
    ],
  },
  {
    id: "digital-marketing",
    name: "Digital Marketing",
    services: [
      "Social Media Management",
      "Ad Campaign Management",
      "SEO Optimization",
      "Email Marketing",
      "Brand Identity & Graphic Design",
      "Conversion Rate Optimization (CRO)",
      "Data Analysis & Reporting",
      "Newsletters",
      "Creative Media (Graphic Design, Video, Photography)",
      "Content Marketing Strategy",
      "Influencer Marketing Campaigns",
      "Digital PR & Reputation Management",
    ],
  },
  {
    id: "web-development",
    name: "Web & App Development",
    services: [
      "Website & Mobile App Development",
      "Landing Page Creation",
      "Functional Websites",
      "Tracking & Analytics",
      "Booking Schedule Systems",
      "Payment Methods Integration",
      "API Development & Integrations",
      "Custom Software Development",
      "Progressive Web Apps (PWAs)",
      "QR Code Menu Systems",
      "Responsive Design Implementation",
      "Web Application Development",
    ],
  },
  {
    id: "customer-success",
    name: "Customer Success",
    services: [
      "CRM Implementation",
      "Customer Journey Mapping & Feedback",
      "Feedback & Survey Systems",
      "Communication Platforms (IVR, Unified)",
      "Customer Portals",
      "Knowledge Hubs",
      "Help Desks Implementations",
      "CRM & Communication Integration",
      "Customer Loyalty Programs",
      "Customer Data Platforms (CDPs)",
      "Omnichannel Customer Experience",
    ],
  },
  {
    id: "payment-commerce",
    name: "Payment & Commerce Solutions",
    services: [
      "Payment Gateway Integration",
      "POS Systems Implementation",
      "Buy Now, Pay Later (BNPL) Systems",
      "POS Integrations",
      "Subscription Billing / Invoicing",
      "E-Commerce Solutions & Integrations",
      "Self-Checkout Machines",
      "Digital Price Tags & Smart Inventory",
      "Self-Ordering Kiosks",
      "RFID-Based Checkout Solutions",
      "AI-Powered Smart Carts",
      "Mobile Payment Solutions",
      "Multi-currency Payment Processing",
    ],
  },
  {
    id: "data-analytics",
    name: "Data & Analytics",
    services: [
      "Data Warehousing & Storage",
      "Real-Time Data Tracking & Insights",
      "Big Data Solutions & Processing",
      "Blockchain for Business Transactions",
      "Blockchain-Powered Business Solutions",
      "Data Protection & Encryption",
      "Business Intelligence Dashboards",
      "Data Visualization Tools",
      "Data Integration & ETL Processes",
      "Customer Data Analysis",
      "Predictive Analytics Implementations",
    ],
  },
  {
    id: "it-security",
    name: "IT & Cybersecurity",
    services: [
      "Security Audits & Vulnerability Assessments",
      "Cloud Computing & Migration",
      "IT Support & Helpdesk Services",
      "Enterprise Resource Planning (ERP) Systems",
      "Security Training for Organizations",
      "Threat Detection & Response",
      "Security Systems Implementations",
      "IT Infrastructure Setup",
      "Network Security Solutions",
      "Identity & Access Management",
      "Disaster Recovery Planning",
      "Compliance & Regulatory Solutions",
    ],
  },
  {
    id: "automation-logistics",
    name: "Automation & Logistics",
    services: [
      "Workflow Automations",
      "Process Streamlining",
      "Marketing Automations",
      "Sales Automations",
      "Customer Service Automations",
      "Automated Warehouse Solutions",
      "Smart Fleet Management",
      "AI-Powered Demand Forecasting",
      "Supply Chain Optimization",
      "Delivery Management & Last-Mile Logistics",
      "Inventory Management Systems",
      "Route Optimization Solutions",
      "Warehouse Management Systems",
    ],
  },
  {
    id: "communication",
    name: "Communication Systems",
    services: [
      "Unified Communications Systems",
      "AI-Powered Call Centers",
      "IVR System Implementation",
      "Video Conferencing Solutions",
      "Team Collaboration Platforms",
      "Business Phone Systems",
      "Internal Communication Tools",
      "Messaging & Chat Solutions",
      "Communication Analytics",
    ],
  },
  {
    id: "training-knowledge",
    name: "Training & Knowledge",
    services: [
      "Staff Training & Onboarding",
      "E-learning Platform Development",
      "Knowledge Base & Documentation",
      "Virtual Training Environments",
      "Learning Management Systems (LMS)",
      "Skills Assessment Tools",
      "Training Content Development",
      "Certification Programs",
      "Interactive Learning Solutions",
    ],
  },
  {
    id: "emerging-tech",
    name: "Emerging Technologies",
    services: [
      "AI-Powered Edge Computing",
      "5G & IoT Integration",
      "Autonomous Drone Deliveries",
      "Facial Recognition & Biometric Authentication",
      "Smart Parking & Traffic Systems",
      "Public Transport Digitalization",
      "E-Governance & Digital Public Services",
      "Smart Waste Management",
      "Augmented & Virtual Reality Solutions",
      "Digital Twin Technology",
      "Quantum Computing Applications",
      "Sustainable Tech Solutions",
    ],
  },
]

